---

- name: nodejs apt key present
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: apt-transport-https package present
  apt:
    name: apt-transport-https
    state: present

- name: nodejs apt list present
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    filename: nodejs
    state: present
    update_cache: true

- name: nodejs and needed packages present
  apt:
    pkg:
      - build-essential
      - nodejs
    state: present
